In [1]:
import numpy as np
np.__version__

'1.16.2'

In [1]:
L=list(range(10))

In [2]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

In [5]:
L2=[str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

In [7]:
L3=[True,"2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [8]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14,4,2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.random.random((3,3))

array([[0.00810608, 0.61441389, 0.58449531],
       [0.52124723, 0.71481037, 0.22222754],
       [0.49613554, 0.48049381, 0.3358683 ]])

In [19]:
np.random.normal(0,1,(3,3))

array([[ 0.07991779,  0.08150901, -1.33325185],
       [ 1.54068378,  1.24154762, -0.61408031],
       [-0.78056651,  0.27716299,  2.07935   ]])

In [20]:
np.random.randint(0,10,(3,3))

array([[6, 3, 7],
       [6, 7, 0],
       [8, 9, 1]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty(3)

array([1., 1., 1.])

## 陣列屬性 dtype:int,float,"float32",bool

In [23]:
import numpy as np
np.random.seed(0)
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [24]:
print("x3 ndim:",x3.ndim)
print("x3 shape:",x3.shape)
print("x3 size:",x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [25]:
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 4 bytes
nbytes: 240 bytes


In [26]:
print("dtype:",x3.dtype)

dtype: int32


## 陣列取值與取代 
### print(array)變成list,一維位置可用array取值(變成與array形狀一樣)也可用起始值:最末值:間隔
### 二維位置可用兩個陣列取值(兩陣列延伸變成方陣的形狀)也可用起始值:最末值:間隔,起始值:最末值:間隔
### 可用mask
## 陣列變形
### reshape(()),[:,np.newaxis],.ravel()

In [27]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [28]:
x2[0,0]=12

In [29]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [30]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[:5]

array([0, 1, 2, 3, 4])

In [32]:
x[5:]

array([5, 6, 7, 8, 9])

In [33]:
x[::2]

array([0, 2, 4, 6, 8])

In [34]:
x[1::2]

array([1, 3, 5, 7, 9])

In [35]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x[5::-2]

array([5, 3, 1])

In [37]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [38]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [39]:
print(x2[:,0])

[12  7  1]


In [40]:
print(x2[0,:])

[12  5  2  4]


In [41]:
print(x2[0])

[12  5  2  4]


In [42]:
import numpy as np
rand=np.random.RandomState(42)

In [43]:
x=rand.randint(100,size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [44]:
ind=np.array([3,7,4])
x[ind]

array([71, 86, 60])

In [45]:
ind=np.array([[3,7],[4,5]])
x[ind]

array([[71, 86],
       [60, 20]])

In [46]:
x=np.arange(12).reshape((3,4))

In [47]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
row=np.array([0,1,2])
col=np.array([2,1,3])
x[row,col]

array([ 2,  5, 11])

In [50]:
x=np.arange(12).reshape((3,4))

In [51]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
row=np.array([0,1,2])
col=np.array([2,1,3])

In [52]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [53]:
x[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [54]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
x[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [56]:
mask=np.array([1,0,1,0],dtype=bool)

In [57]:
mask

array([ True, False,  True, False])

In [58]:
x[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [59]:
x=np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [60]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [61]:
animals=['cat','dog','bat']
for animal in animals:
    print(animal)
for index,animal in enumerate(animals):
    print(index,animal)

cat
dog
bat
0 cat
1 dog
2 bat


In [62]:
list1=[x for x in range(10)]
list2=[x+1 for x in range(10)]
list3=[x for x in range(10) if x%2==0]
list4=[x*2 for x in range(10) if x%2==0]

## 陣列複製

In [63]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [64]:
x2_sub=x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [65]:
x2_sub[0,0]=99

In [66]:
print(x2_sub)

[[99  5]
 [ 7  6]]


In [67]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [68]:
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [69]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [70]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## 陣列取代與修改

In [71]:
x=np.arange(10)
i=np.array([2,1,8,4])
x[i]=99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [72]:
x[i]-=10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [73]:
x=np.zeros(10)
x[[0,0]]=[4,6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [74]:
i=[2,3,3,4,4,4]
x[i]+=1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [75]:
x=np.zeros(10)
np.add.at(x,i,1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]


## 陣列插入:append,insert,extend、移出:pop

In [3]:
ls=[6,4,5]
print(ls,ls[2])
print(ls[-1])
ls[2]="py"
print(ls)
ls.append("bar")
print(ls)
ele=ls.pop()
print(ele,ls)

[6, 4, 5] 5
5
[6, 4, 'py']
[6, 4, 'py', 'bar']
bar [6, 4, 'py']


In [77]:
list1=[1,2,3,4,5,6]
list1.insert(3,8)
list1

[1, 2, 3, 8, 4, 5, 6]

In [78]:
list1.append([8,9])
list1

[1, 2, 3, 8, 4, 5, 6, [8, 9]]

In [80]:
list1.extend([8,9])
list1

[1, 2, 3, 8, 4, 5, 6, [8, 9], 8, 9, 8, 9]

In [81]:

list1.pop(3)
list1

[1, 2, 3, 4, 5, 6, [8, 9], 8, 9, 8, 9]

## 陣列串接concatenate([array,array])陣列拿掉外面的括號串接(axis=1)時等於np.hstack,vstack([array,array]),hstack([array,array])

In [149]:
",".join(["b","a"])

'b,a'

In [82]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [83]:
z=[99,99,99]
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


In [84]:
grid=np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [85]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [86]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [87]:
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## 陣列分割np.split(array,[切割點]),np.hsplit(array,[切割點]),np.vsplit(array,[切割點])

In [88]:
x=[1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])

In [89]:
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [90]:
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [91]:
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [92]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 結構化陣列(陣列元素可設定名,type,形狀)

In [93]:
name=["Alice","Bob","Cathy","Doug"]
age=[25,45,37,19]
weight=[55.0,85.5,68.0,61.5]

In [94]:
data=np.zeros(4,dtype={'names':('name','age','weight'),'formats':('U10','i4','f8')})

In [95]:
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [96]:
data["name"]=name
data["age"]=age
data["weight"]=weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [97]:
np.dtype({'names':('name','age','weight'),'formats':('U10','i4','f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [98]:
np.dtype({'names':('name','age','weight'),'formats':((np.str_,10),int,np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [99]:
np.dtype([('name','S10'),('age','i4'),('weight','f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [100]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [86]:
tp=np.dtype([('id','i8'),('mat','f8',(3,3))])
X=np.zeros(1,dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 陣列排列np.sort,np.partition,sorted

In [101]:
def selection_sort(x):
    for i in range(len(x)):
        swap=i+np.argmin(x[i:])
        (x[i],x[swap])=(x[swap],x[i])
    return(x)
x=np.array([2,1,4,3,5])
selection_sort(x)

array([1, 2, 3, 4, 5])

In [106]:
x=np.array([2,1,4,3,5])
np.sort(x)
x.sort()
print(x)
x=np.array([2,1,4,3,5])
i=np.argsort(x)
print(i)
x[i]

[1 2 3 4 5]
[1 0 3 2 4]


array([1, 2, 3, 4, 5])

In [108]:
rand=np.random.RandomState(42)
X=rand.randint(0,10,(4,6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [109]:
np.sort(X,axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [110]:
rand=np.random.RandomState(42)
X=rand.randint(0,10,(4,6))
print(X)
np.sort(X,axis=0)
np.sort(X,axis=1)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [112]:
x=np.array([7,2,3,1,6,5,4])
np.partition(x,3)

array([2, 1, 3, 4, 6, 5, 7])

In [113]:
np.partition(X,2,axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])

## 陣列計算reduce,accumulate,count_nonzero=sum

In [114]:
x=np.arange(4)
print("x=",x)
print("x+5=",x+5)
print("x-5=",x-5)
print("x/2=",x/2)
print("x//2",x//2)

x= [0 1 2 3]
x+5= [5 6 7 8]
x-5= [-5 -4 -3 -2]
x/2= [0.  0.5 1.  1.5]
x//2 [0 0 1 1]


In [115]:
print("-x=",-x)
print("x**2=",x**2)
print("x%2=",x%2)

-x= [ 0 -1 -2 -3]
x**2= [0 1 4 9]
x%2= [0 1 0 1]


In [116]:
np.add(x,2)

array([2, 3, 4, 5])

In [117]:
np.subtract(x,2)
np.multiply(x,2)
np.divide(x,2)
np.floor_divide(x,2)
np.power(x,2)
np.mod(x,2)

array([0, 1, 0, 1], dtype=int32)

In [118]:
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [119]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [120]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [121]:
x=np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [122]:
theta=np.linspace(0,np.pi,3)

In [123]:
print("theta=",theta)
print("sin(theta)=",np.sin(theta))
print("cos(theta)=",np.cos(theta))
print("tan(theta)=",np.tan(theta))

theta= [0.         1.57079633 3.14159265]
sin(theta)= [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta)= [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta)= [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [124]:
x=[-1,0,1]
print("x=",x)
print("arcsin(x)=",np.arcsin(x))
print("arccos(x)=",np.arccos(x))
print("arctan(x)=",np.arctan(x))

x= [-1, 0, 1]
arcsin(x)= [-1.57079633  0.          1.57079633]
arccos(x)= [3.14159265 1.57079633 0.        ]
arctan(x)= [-0.78539816  0.          0.78539816]


In [125]:
x=[1,2,3]
print("x=",x)
print("e^x=",np.exp(x))
print("2^x=",np.exp2(x))
print("3^x=",np.power(3,x))

x= [1, 2, 3]
e^x= [ 2.71828183  7.3890561  20.08553692]
2^x= [2. 4. 8.]
3^x= [ 3  9 27]


In [126]:
x=[1,2,4,10]
print("x=",x)
print("ln(x)=",np.log(x))
print("log2(x)=",np.log2(x))
print("log10(x)=",np.log10(x))

x= [1, 2, 4, 10]
ln(x)= [0.         0.69314718 1.38629436 2.30258509]
log2(x)= [0.         1.         2.         3.32192809]
log10(x)= [0.         0.30103    0.60205999 1.        ]


In [127]:
x=[0,0.001,0.01,0.1]
print("exp(x)-1=",np.expm1(x))
print("log(1+x)=",np.log1p(x))

exp(x)-1= [0.         0.0010005  0.01005017 0.10517092]
log(1+x)= [0.         0.0009995  0.00995033 0.09531018]


In [128]:
from scipy import special

In [129]:
x=[1,5,10]
print("gamma(x)=",special.gamma(x))
print("ln|gamma(x)|=",special.gammaln(x))
print("beta(x,2)=",special.beta(x,2))

gamma(x)= [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)|= [ 0.          3.17805383 12.80182748]
beta(x,2)= [0.5        0.03333333 0.00909091]


In [130]:
x=np.array([0,0.3,0.7,1.0])
print("erf(x)=",special.erf(x))
print("erfc(x)=",special.erfc(x))
print("erfinv(x)=",special.erfinv(x))

erf(x)= [0.         0.32862676 0.67780119 0.84270079]
erfc(x)= [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)= [0.         0.27246271 0.73286908        inf]


In [131]:
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [132]:
y=np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [133]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [134]:
np.multiply.reduce(x)

120

In [135]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [136]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [109]:
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [137]:
M=np.random.random((3,4))
print(M)

[[0.65279032 0.63505887 0.99529957 0.58185033]
 [0.41436859 0.4746975  0.6235101  0.33800761]
 [0.67475232 0.31720174 0.77834548 0.94957105]]


In [139]:
M.sum()

7.435453494015987

In [140]:
M.sum(axis=0)

array([1.74191123, 1.42695812, 2.39715515, 1.869429  ])

In [141]:
M.max(axis=1)

array([0.99529957, 0.6235101 , 0.94957105])

In [142]:
print("Mean height:",heights.mean())
print("Standard height:",heights.std())
print("Minimum height:",heights.min())
print("Maximum height:",heights.max())

NameError: name 'heights' is not defined

In [ ]:
print("25th percentile:",np.percentile(heights,25))
print("Median:",np.median(heights))
print("75th percentile:",np.percentile(heights,75))

In [145]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [146]:
np.count_nonzero(x<6)

8

In [147]:
np.sum(x<6)

8

In [143]:
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
np.count_nonzero(x<6)
np.sum(x<6)
np.sum(x<6,axis=1)
np.any(x>8)
np.all(x<10)
np.all(x<8,axis=1)

array([ True, False,  True])